import { LucideIcon } from "lucide-react";
import * as Icons from "lucide-react";

export interface PlayerClassAbility {
  name: string;
  iconName: string;
  description: string;
  /** Cooldown in seconds (real-time in battle). */
  cooldown: number;
  manaCost: number;
}

export interface PlayerClass {
  health: number;
  attackMin: number;
  attackMax: number;
  mana: number;
  maxMana: number;
  description: string;
  abilities: PlayerClassAbility[];
}

export const getIconByName = (name: string): LucideIcon => {
  const icon = (Icons as unknown as Record<string, LucideIcon>)[name];
  return icon && typeof icon === "function" ? icon : Icons.HelpCircle;
};

export const PLAYER_CLASSES: Record<string, PlayerClass> = {
  Warrior: {
    health: 1910,
    attackMin: 35,
    attackMax: 41,
    mana: 118,
    maxMana: 118,
    description: "Frontline duelist — shields and shouts",
    abilities: [
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 48-62 damage",
        cooldown: 5,
        manaCost: 24,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 30 health points",
        cooldown: 3,
        manaCost: 5,
      },
      {
        name: "Battle Shout",
        iconName: "Megaphone",
        description: "Increase attack by 35%",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Mana Heal",
        iconName: "Heart",
        description: "Convert 15 mana to 30 health",
        cooldown: 5,
        manaCost: 0,
      },
      {
        name: "Cleave",
        iconName: "Sword",
        description: "deal 38-52 damage",
        cooldown: 4,
        manaCost: 18,
      },
      {
        name: "Fortifying Cry",
        iconName: "Shield",
        description: "Gain a shield that blocks 35 damage everyturn",
        cooldown: 6,
        manaCost: 22,
      },
    ],
  },
  Slayer: {
    health: 1900,
    attackMin: 35,
    attackMax: 41,
    mana: 118,
    maxMana: 118,
    description: "Aggressive striker — high burst windows",
    abilities: [
      {
        name: "Battle Shout",
        iconName: "Megaphone",
        description: "Increase attack by 40%",
        cooldown: 10,
        manaCost: 30,
      },
      {
        name: "Rage",
        iconName: "Flame",
        description: "Increase attack by 25% deal 28 damage ",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Execute",
        iconName: "Sword",
        description:
          "If enemy is under 10% health: instantly kill; otherwise deal 42 damage",
        cooldown: 9,
        manaCost: 50,
      },
      {
        name: "Whirlwind",
        iconName: "Wind",
        description: "Whirlwind 52 damage to enemy, 14 self damage",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Bloodletting",
        iconName: "Droplets",
        description: "Inflict 5 bleed damage",
        cooldown: 4,
        manaCost: 15,
      },
      {
        name: "Ground Slam",
        iconName: "Hammer",
        description: "deal 34-48 damage",
        cooldown: 5,
        manaCost: 25,
      },
    ],
  },
  Rogue: {
    health: 1880,
    attackMin: 34,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Bleeds and steals — tempo fighter",
    abilities: [
      {
        name: "Intimidate",
        iconName: "Skull",
        description: "Increase attack by 35% ",
        cooldown: 8,
        manaCost: 20,
      },

      {
        name: "Bleeding Strike",
        iconName: "Zap",
        description: "Inflict 6 bleed damage",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Life Steal",
        iconName: "Heart",
        description: "Deal 20 damage and steal 20 health",
        cooldown: 6,
        manaCost: 30,
      },
      {
        name: "Vampiric Strike",
        iconName: "Droplets",
        description: "Vampiric strike deal 40-80 damage with 100% healing",
        cooldown: 6,
        manaCost: 36,
      },
      {
        name: "Eviscerate",
        iconName: "Sword",
        description: "deal 28-44 damage",
        cooldown: 4,
        manaCost: 31,
      },
      {
        name: "Shadowstep",
        iconName: "Moon",
        description: "Become untargetable for 1 turn",
        cooldown: 7,
        manaCost: 35,
      },
    ],
  },

  Archer: {
    health: 1870,
    attackMin: 34,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Bow skirmisher — steady pressure",
    abilities: [
      {
        name: "Rapid Fire",
        iconName: "Target",
        description: "Deal 20 damage and increase attack by 30%",
        cooldown: 4,
        manaCost: 25,
      },
      {
        name: "Power Shot",
        iconName: "Target",
        description: "Deal 28 damage and increase attack by 40%",
        cooldown: 5,
        manaCost: 32,
      },
      {
        name: "Battle Fury",
        iconName: "Crosshair",
        description: "Increase attack by 60% ",
        cooldown: 7,
        manaCost: 35,
      },
      {
        name: "Berserker Shot",
        iconName: "Eye",
        description: "Deal 30 damage and increase attack by 45% ",
        cooldown: 6,
        manaCost: 32,
      },
      {
        name: "Volley",
        iconName: "Target",
        description: "deal 24-38 damage",
        cooldown: 4,
        manaCost: 35,
      },
      {
        name: "Hunter's Mark",
        iconName: "Crosshair",
        description: "Increase attack by 28%",
        cooldown: 5,
        manaCost: 22,
      },
    ],
  },
  Ranger: {
    health: 1860,
    attackMin: 34,
    attackMax: 39,
    mana: 120,
    maxMana: 120,
    description: "Mobile archer — burst and focus",
    abilities: [
      {
        name: "Quick Shot",
        iconName: "Target",
        description: "Fire three quick shots",
        cooldown: 3,
        manaCost: 20,
      },

      {
        name: "Aimed Shot",
        iconName: "Target",
        description: "Deal 35 damage",
        cooldown: 5,
        manaCost: 35,
      },
      {
        name: "Explosive Barrage",
        iconName: "Zap",
        description: "Deal 22 damage and increase attack by 25% ",
        cooldown: 5,
        manaCost: 26,
      },
      {
        name: "Focused Strike",
        iconName: "ArrowRight",
        description: "Deal 25 damage and increase attack by 50%",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Piercing Arrow",
        iconName: "Target",
        description: "deal 32-46 damage",
        cooldown: 5,
        manaCost: 38,
      },
      {
        name: "Skirmisher's Pace",
        iconName: "Zap",
        description: "Restore 18 mana",
        cooldown: 5,
        manaCost: 0,
      },
    ],
  },
  Mage: {
    health: 1840,
    attackMin: 32,
    attackMax: 38,
    mana: 132,
    maxMana: 132,
    description: "Arcane duelist — fire and frost",
    abilities: [
      {
        name: "Fireball",
        iconName: "Flame",
        description: "Deal 20-30 fire damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Mana Surge",
        iconName: "Sparkles",
        description: "Increase spell damage by 28% for next turn",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Arcane Bolt",
        iconName: "Bolt",
        description: "Deal 30 damage",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Ice Lance",
        iconName: "Snowflake",
        description: "Deal 15-25 damage",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Arcane Barrage",
        iconName: "Sparkles",
        description: "deal 26-38 damage",
        cooldown: 4,
        manaCost: 28,
      },
      {
        name: "Blink Ward",
        iconName: "Shield",
        description: "Increase spell damage by 15%",
        cooldown: 5,
        manaCost: 20,
      },
    ],
  },

  Oracle: {
    health: 1830,
    attackMin: 32,
    attackMax: 37,
    mana: 132,
    maxMana: 132,
    description: "Seer — marks and bolts",
    abilities: [
      {
        name: "Astral Bolt",
        iconName: "Bolt",
        description: "Deal 24-36 damage",
        cooldown: 3,
        manaCost: 25,
      },

      {
        name: "Clairvoyance",
        iconName: "Sparkles",
        description: "Increase spell damage by 25%",
        cooldown: 5,
        manaCost: 20,
      },
      {
        name: "Foresight",
        iconName: "Eye",
        description: "Increase attack by 22% ",
        cooldown: 5,
        manaCost: 20,
      },
      {
        name: "Prophetic Mark",
        iconName: "Crosshair",
        description: "permanently counterattack 22% of damage taken",
        cooldown: 4,
        manaCost: 25,
      },
      {
        name: "Starfall",
        iconName: "Sparkles",
        description: "deal 32-48 damage",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Second Sight",
        iconName: "Eye",
        description: "Restore 22 health points",
        cooldown: 4,
        manaCost: 18,
      },
    ],
  },
  Healer: {
    health: 1850,
    attackMin: 32,
    attackMax: 37,
    mana: 132,
    maxMana: 132,
    description: "Support striker — heals and smites",
    abilities: [
      {
        name: "Holy Smite",
        iconName: "Flame",
        description: "Deal 20-40 holy damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Heal",
        iconName: "Heart",
        description: "Restore 25% health",
        cooldown: 3,
        manaCost: 25,
      },

      {
        name: "Rejuvenation",
        iconName: "Heart",
        description: "Permanently heal 10 health every turn",
        cooldown: 6,
        manaCost: 35,
      },
      {
        name: "Blessing of Light",
        iconName: "Sparkles",
        description:
          "Increase spell damage by 35%, increase attack by 22%, and restore 8% health",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Holy Nova",
        iconName: "Flame",
        description: "Deal 18-28 holy damage",
        cooldown: 3,
        manaCost: 22,
      },
      {
        name: "Sanctuary",
        iconName: "Shield",
        description: "Gain a shield that blocks 40 damage everyturn",
        cooldown: 6,
        manaCost: 32,
      },
    ],
  },

  Warlord: {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Battlefield commander",
    abilities: [
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 30-50 damage",
        cooldown: 2,
        manaCost: 50,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 30 health points",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Battle Shout",
        iconName: "Megaphone",
        description: "Increase attack by 40% ",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Life Steal",
        iconName: "Heart",
        description: "Deal 20 damage and steal 20 health",
        cooldown: 6,
        manaCost: 24,
      },
      {
        name: "Commanding Strike",
        iconName: "Sword",
        description: "Deal 44-62 damage,Increase attack by 38%",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Sundering Blow",
        iconName: "Hammer",
        description: "deal 36-50 damage",
        cooldown: 5,
        manaCost: 32,
      },
    ],
  },
  Berserker: {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Reckless Swing",
        iconName: "Sword",
        description: "Deal 25-40 damage but take 5 self-damage",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Berserker Rage",
        iconName: "Flame",
        description: "Increase attack by 38%, take 10 self-damage",
        cooldown: 8,
        manaCost: 40,
      },
      {
        name: "Execute",
        iconName: "Sword",
        description:
          "If enemy is under 12% health: instantly kill; otherwise deal 52 damage",
        cooldown: 9,
        manaCost: 45,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 30 health points",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Blood Frenzy",
        iconName: "Flame",
        description:
          "Attack twice for 30-40 damage each, but take 15 self-damage",
        cooldown: 7,
        manaCost: 50,
      },
      {
        name: "Crushing Blow",
        iconName: "Sword",
        description: "deal 42-58 damage",
        cooldown: 5,
        manaCost: 32,
      },
    ],
  },

  Paladin: {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Divine Smite",
        iconName: "Sparkles",
        description: "Deal 58-72 holy damage",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Lay on Hands",
        iconName: "Heart",
        description: "restore 32% health",
        cooldown: 10,
        manaCost: 40,
      },
      {
        name: "Mana Heal",
        iconName: "Heart",
        description: "Convert 10 mana to 100 health",
        cooldown: 5,
        manaCost: 0,
      },
      {
        name: "Blessing of Light",
        iconName: "Sparkles",
        description:
          "Increase spell damage by 25%, increase attack by 25%, and restore 5% health",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Divine Shield",
        iconName: "Shield",
        description: "Repel abilities for 4 turns",
        cooldown: 10,
        manaCost: 35,
      },
      {
        name: "Avenger's Rebuke",
        iconName: "Flame",
        description: "Deal 24-36 holy damage",
        cooldown: 4,
        manaCost: 24,
      },
    ],
  },
  Beastguard: {
    health: 1890,
    attackMin: 35,
    attackMax: 41,
    mana: 120,
    maxMana: 120,
    description: "Skirmisher and pet pressure",
    abilities: [
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "Deal 12-18 damage",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 50 health points",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Battle Shout",
        iconName: "Megaphone",
        description: "Increase attack by 40% ",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Quick Shot",
        iconName: "Target",
        description: "Fire three quick shots",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Summon Wolf",
        iconName: "Dog",
        description: "Summon a wolf that deals 12 damage per turn permanently",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Savage Maul",
        iconName: "Sword",
        description: "deal 34-50 damage",
        cooldown: 5,
        manaCost: 26,
      },
    ],
  },
  "Death Knight": {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Bleeding Strike",
        iconName: "Zap",
        description: "Inflict 6 bleed damage",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Vampiric Strike",
        iconName: "Droplets",
        description: "Vampiric strike deal 40-80 damage with 100% healing",
        cooldown: 6,
        manaCost: 28,
      },
      {
        name: "Battle Shout",
        iconName: "Megaphone",
        description: "Increase attack by 40% ",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Whirlwind",
        iconName: "Wind",
        description: "Whirlwind 25 damage to enemy, 8 self damage",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Shadow Ambush",
        iconName: "Moon",
        description:
          "Become untargetable for 1 turn, then strike next turn for 60-90 damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Frost Strike",
        iconName: "Snowflake",
        description: "deal 38-54 damage",
        cooldown: 4,
        manaCost: 28,
      },
    ],
  },

  "Dragon Slayer": {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Battle Shout",
        iconName: "Megaphone",
        description: "Increase attack by 32%",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Mana Heal",
        iconName: "Heart",
        description: "Convert 15 mana to 30 health",
        cooldown: 5,
        manaCost: 0,
      },
      {
        name: "Prophetic Mark",
        iconName: "Crosshair",
        description: "permanently counterattack 22% of damage taken",
        cooldown: 4,
        manaCost: 25,
      },
      {
        name: "Clairvoyance",
        iconName: "Sparkles",
        description: "Increase spell damage by 25%",
        cooldown: 5,
        manaCost: 20,
      },
      {
        name: "Judgment of Fate",
        iconName: "Sword",
        description:
          "Deal 44-62 damage. If enemy is below 35% health, deal double damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Drakefang Cleave",
        iconName: "Flame",
        description: "deal 40-56 damage",
        cooldown: 5,
        manaCost: 50,
      },
    ],
  },
  Knight: {
    health: 1920,
    attackMin: 35,
    attackMax: 41,
    mana: 118,
    maxMana: 118,
    description: "Armored hybrid — bow and blade",
    abilities: [
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 30-50 damage",
        cooldown: 2,
        manaCost: 50,
      },
      {
        name: "Rapid Fire",
        iconName: "Target",
        description: "Deal 38 damage and increase attack by 28%",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Power Shot",
        iconName: "Target",
        description: "Deal 42 damage and increase attack by 32%",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 100 health points",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Judgment of Fate",
        iconName: "Sword",
        description:
          "Deal 44-68 damage. If enemy is below 18% health, deal double damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Lance Throw",
        iconName: "Target",
        description: "deal 30-46 damage",
        cooldown: 4,
        manaCost: 32,
      },
    ],
  },
  Shaman: {
    health: 1880,
    attackMin: 35,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Spirit archer",
    abilities: [
      {
        name: "Aimed Shot",
        iconName: "Target",
        description: "Deal 28-38 damage",
        cooldown: 5,
        manaCost: 35,
      },
      {
        name: "Power Shot",
        iconName: "Target",
        description: "Deal 28 damage and increase attack by 50%",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 30 health points",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Clairvoyance",
        iconName: "Sparkles",
        description: "Increase spell damage by 50%",
        cooldown: 5,
        manaCost: 20,
      },
      {
        name: "Execute",
        iconName: "Sword",
        description:
          "If enemy is under 25% health: instantly kill; otherwise deal 100 damage",
        cooldown: 8,
        manaCost: 45,
      },
      {
        name: "Spirit Link",
        iconName: "Heart",
        description: "Restore 28 health points",
        cooldown: 5,
        manaCost: 22,
      },
    ],
  },
  Crossbowman: {
    health: 1890,
    attackMin: 35,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Heavy crossbow — executes and volleys",
    abilities: [
      {
        name: "Aimed Shot",
        iconName: "Target",
        description: "Deal 48-68 damage",
        cooldown: 5,
        manaCost: 35,
      },
      {
        name: "Power Shot",
        iconName: "Target",
        description: "Deal 58 damage and increase attack by 50%",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 30 health points",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Clairvoyance",
        iconName: "Sparkles",
        description: "Increase spell damage by 28%",
        cooldown: 5,
        manaCost: 20,
      },
      {
        name: "Starlight Volley",
        iconName: "Sparkles",
        description:
          "Unleash a barrage of astral arrows dealing 50-70 damage 5 times",
        cooldown: 8,
        manaCost: 60,
      },
      {
        name: "Armor Piercer",
        iconName: "Crosshair",
        description: "deal 44-62 damage",
        cooldown: 5,
        manaCost: 32,
      },
    ],
  },

  Wizard: {
    health: 1840,
    attackMin: 32,
    attackMax: 38,
    mana: 128,
    maxMana: 128,
    description: "Battle cleric — wards and smites",
    abilities: [
      {
        name: "Rejuvenation",
        iconName: "Heart",
        description: "Permanently heal 10 health every turn",
        cooldown: 6,
        manaCost: 35,
      },
      {
        name: "Holy Smite",
        iconName: "Flame",
        description: "Deal 20-40 holy damage",
        cooldown: 3,
        manaCost: 25,
      },

      {
        name: "Mana Surge",
        iconName: "Sparkles",
        description: "Increase spell damage by 28% for next turn",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 100 damage everyturn",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Searing Light",
        iconName: "Bolt",
        description: "deal 28-40 damage",
        cooldown: 3,
        manaCost: 22,
      },
      {
        name: "Gods's Wrath",
        iconName: "Flame",
        description:
          "Passive: When losing health, increase attack by 1% (stacks)",
        cooldown: 0,
        manaCost: 0,
      },
    ],
  },

  Warlock: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Shadow pact — drains and imps",
    abilities: [
      {
        name: "Shadow Bolt",
        iconName: "Bolt",
        description: "Deal 18-24 shadow damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Life Tap",
        iconName: "Heart",
        description: "Lose 10 health to gain 25 mana",
        cooldown: 3,
        manaCost: 0,
      },
      {
        name: "Summon Imp",
        iconName: "Flame",
        description: "Summon pet that deals 8 dmg for every turn",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Vampiric Strike",
        iconName: "Droplets",
        description: "Vampiric strike deal 40-80 damage with 100% healing",
        cooldown: 6,
        manaCost: 28,
      },
      {
        name: "Swap Stats",
        iconName: "RefreshCw",
        description: "Swap your health with opponent",
        cooldown: 8,
        manaCost: 40,
      },
      {
        name: "Fel Spike",
        iconName: "Skull",
        description: "deal 32-46 shadow damage",
        cooldown: 4,
        manaCost: 26,
      },
    ],
  },

  Battlemage: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Spellblade hybrid",
    abilities: [
      {
        name: "Battle Shout",
        iconName: "Megaphone",
        description: "Increase attack by 32%",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Poison",
        iconName: "Zap",
        description: "Inflict 20 poison damage",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Fireball",
        iconName: "Flame",
        description: "Deal 20-30 fire damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Mana Surge",
        iconName: "Sparkles",
        description: "Increase spell damage by 28% for next turn",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Arcane Bolt",
        iconName: "Bolt",
        description: "Deal 30 damage",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Blade Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 48 damage everyturn",
        cooldown: 6,
        manaCost: 30,
      },
    ],
  },
  Enchanter: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Crowd control and hexes",
    abilities: [
      {
        name: "Fireball",
        iconName: "Flame",
        description: "Deal 20-30 fire damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Mana Heal",
        iconName: "Heart",
        description: "Convert 15 mana to 30 health",
        cooldown: 5,
        manaCost: 0,
      },
      {
        name: "Intimidate",
        iconName: "Skull",
        description: "Increase attack by 20% ",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Bleeding Strike",
        iconName: "Zap",
        description: "Inflict 6 bleed damage",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Shadow Ambush",
        iconName: "Moon",
        description:
          "Become untargetable for 1 turn, then strike next turn for 48-62 damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Hex Bolt",
        iconName: "Bolt",
        description: "deal 24-36 damage",
        cooldown: 3,
        manaCost: 28,
      },
    ],
  },

  Priest: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Holy support",
    abilities: [
      {
        name: "Rejuvenation",
        iconName: "Heart",
        description: "Permanently heal 10 health every turn",
        cooldown: 6,
        manaCost: 35,
      },
      {
        name: "Blessing of Light",
        iconName: "Sparkles",
        description:
          "Increase spell damage by 25%, increase attack by 25%, and restore 5% health",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Divine Shield",
        iconName: "Shield",
        description: "Repel abilities for 4 turns",
        cooldown: 10,
        manaCost: 35,
      },
      {
        name: "Lay on Hands",
        iconName: "Heart",
        description: "restore 32% health",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 100 damage everyturn",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Smite Evil",
        iconName: "Flame",
        description: "Deal 22-34 holy damage",
        cooldown: 3,
        manaCost: 20,
      },
    ],
  },
  "Elemental Warden": {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Four elements",
    abilities: [
      {
        name: "Fire Blast",
        iconName: "Flame",
        description: "Deal 25-35 fire damage and inflict 5 damage everyturn",
        cooldown: 3,
        manaCost: 35,
      },
      {
        name: "Water Spout",
        iconName: "Droplets",
        description: "Deal 50 water damage , heal 30 health",
        cooldown: 4,
        manaCost: 40,
      },
      {
        name: "Earth Tremor",
        iconName: "Mountain",
        description: "Deal 30-40 earth damage and increase 30% spell damage",
        cooldown: 5,
        manaCost: 35,
      },
      {
        name: "Wind Slash",
        iconName: "Wind",
        description: "Deal 15-25 wind damage and increase your attack by 30%",
        cooldown: 3,
        manaCost: 22,
      },
      {
        name: "Spirit Bolt",
        iconName: "Sparkles",
        description: "Deal 35-45 spirit damage and restore 15 mana",
        cooldown: 4,
        manaCost: 38,
      },
      {
        name: "Elemental Surge",
        iconName: "Zap",
        description: "Increase spell damage by 20%",
        cooldown: 5,
        manaCost: 24,
      },
    ],
  },

  Lich: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Undying sorcerer",
    abilities: [
      {
        name: "Shadow Bolt",
        iconName: "Bolt",
        description: "Deal 18-24 shadow damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Life Tap",
        iconName: "Heart",
        description: "Lose 10 health to gain 25 mana",
        cooldown: 3,
        manaCost: 0,
      },
      {
        name: "Curse of Agony",
        iconName: "Skull",
        description: "8 damage per turn for 1 turn",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Shadow Ambush",
        iconName: "Moon",
        description:
          "Become untargetable for 1 turn, then strike next turn for 48-64 damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Intimidate",
        iconName: "Skull",
        description: "Increase attack by 20% ",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Soul Harvest",
        iconName: "Moon",
        description: "deal 36-52 damage",
        cooldown: 5,
        manaCost: 32,
      },
    ],
  },

  Druid: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Shapeshifter and beasts",
    abilities: [
      {
        name: "Summon Wolf",
        iconName: "Dog",
        description: "Summon a wolf that deals 12 damage per turn permanently",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Wolf Howl",
        iconName: "Triangle",
        description: "Empower your wolf: it deals 35% more damage every turn",
        cooldown: 8,
        manaCost: 55,
      },
      {
        name: "Fear Howl",
        iconName: "Skull",
        description: "Become untargetable for 3 turns (stealth mode)",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Heal",
        iconName: "Heart",
        description: "Restore 25 health points",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 100 damage everyturn",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Thorn Lash",
        iconName: "Target",
        description: "Inflict 4 bleed damage",
        cooldown: 4,
        manaCost: 18,
      },
    ],
  },
  Necromancer: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Minion master",
    abilities: [
      {
        name: "Life Tap",
        iconName: "Heart",
        description: "Lose 20 health to gain 100 mana",
        cooldown: 5,
        manaCost: 1,
      },
      {
        name: "Summon Skeleton",
        iconName: "Skull",
        description:
          "Summon a skeleton that deals 25 damage per turn for 5 turns (stacks)",
        cooldown: 3,
        manaCost: 30,
      },
      {
        name: "Summon Zombie",
        iconName: "Zap",
        description:
          "Summon a zombie that deals 28 damage per turn for 5 turns (stacks)",
        cooldown: 3,
        manaCost: 30,
      },
      {
        name: "Summon Wraith",
        iconName: "Moon",
        description:
          "Summon a wraith that deals 30 damage per turn for 5 turns (stacks)",
        cooldown: 3,
        manaCost: 30,
      },
      {
        name: "Necromancy Mastery",
        iconName: "Sparkles",
        description: "All summoned creatures deal 35% more damage everyturn",
        cooldown: 10,
        manaCost: 60,
      },
      {
        name: "Bone Spear",
        iconName: "Skull",
        description: "deal 34-50 damage",
        cooldown: 4,
        manaCost: 28,
      },
    ],
  },
  Witcher: {
    health: 1910,
    attackMin: 35,
    attackMax: 41,
    mana: 125,
    maxMana: 125,
    description: "Monster-slaying swordsman — signs and alchemy.",
    abilities: [
      { name: "Igni Sign", iconName: "Flame", description: "Deal 52–68 fire damage", cooldown: 5, manaCost: 45 },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 55 health points",
        cooldown: 3,
        manaCost: 5,
      },
      {
        name: "Blood Frenzy",
        iconName: "Flame",
        description: "Attack twice for 40-52 damage each, but take 15 self-damage",
        cooldown: 7,
        manaCost: 50,
      },
      {
        name: "Mutagens",
        iconName: "Beaker",
        description: "Passive: Increase attack by 28% while above 50% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Monster Killer",
        iconName: "BookOpen",
        description: "Passive: Increase spell damage by 28% while under 50% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Alchemy Mastery",
        iconName: "FlaskRound",
        description: "Passive: All healing received is 35% stronger while under 50% health.",
        cooldown: 0,
        manaCost: 0,
      },
    ],
  },
  TaurenChieftain: {
    health: 1940,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Totemic war leader — spirits and endurance.",
    abilities: [
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 58-72 damage",
        cooldown: 5,
        manaCost: 56,
      },
      {
        name: "Prophetic Mark",
        iconName: "Crosshair",
        description: "permanently counterattack 22% of damage taken",
        cooldown: 14,
        manaCost: 55,
      },
      {
        name: "Rage",
        iconName: "Flame",
        description: "Increase attack by 18% deal 38 damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Totemic Strength",
        iconName: "Megaphone",
        description: "Passive: Regenerate 20 health everyturn",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Spirit Endurance",
        iconName: "Heart",
        description: "Passive: Reincarnation ",
        cooldown: 100,
        manaCost: 0,
      },
      {
        name: "Gods's Wrath",
        iconName: "Flame",
        description: "Passive: When losing health, increase attack by 1% (stacks)",
        cooldown: 0,
        manaCost: 0,
      },
    ],
  },
  Invoker: {
    health: 1870,
    attackMin: 34,
    attackMax: 39,
    mana: 132,
    maxMana: 132,
    description: "Elemental master — fire, frost, and lightning.",
    abilities: [
      { name: "Fireball", iconName: "Flame", description: "Deal 52–68 fire damage.", cooldown: 3, manaCost: 35 },
      {
        name: "Summon Infernal",
        iconName: "Skull",
        description: "Summon an Infernal that deals 22 damage per turn for 10 turns.",
        cooldown: 16,
        manaCost: 75,
      },
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 72 damage everyturn",
        cooldown: 12,
        manaCost: 55,
      },
      {
        name: "Elemental Mastery",
        iconName: "Sparkles",
        description: "Passive: Spell immunity.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Mana Overflow",
        iconName: "BatteryCharging",
        description: "Passive: Gain +12 mana at the start of your turn.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Elemental Harmony",
        iconName: "Atom",
        description: "Passive: Every turn gain 3% attack and 2% spell damage (stacks)",
        cooldown: 0,
        manaCost: 0,
      },
    ],
  },
  Archmage: {
    health: 1850,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Supreme arcanist — meteors and control.",
    abilities: [
      { name: "Meteor", iconName: "Flame", description: "Deal 58–78 fire damage", cooldown: 3, manaCost: 45 },
      {
        name: "Blizzard",
        iconName: "Snowflake",
        description: "Deal 52–68 frost damage and slow (−18% attack) for 2 turns.",
        cooldown: 3,
        manaCost: 45,
      },
      {
        name: "Worldbreaker",
        iconName: "Skull",
        description: "Deal 72–92 arcane damage.",
        cooldown: 4,
        manaCost: 50,
      },
      {
        name: "Mana Overflow",
        iconName: "BatteryCharging",
        description: "Passive: Gain +12 mana at the start of your turn.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Mage Lore",
        iconName: "BookOpen",
        description:
          "Passive: Gain 8% spell damage per turn (stacks max 3).",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Temporal Mastery",
        iconName: "Hourglass",
        description: "Passive:Every turn Gain a shield that blocks 42 damage everyturn (stacks)",
        cooldown: 0,
        manaCost: 0,
      },
    ],
  },
  Godslayer: {
    health: 1920,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Relentless duelist — execution and pressure.",
    abilities: [
      {
        name: "Divine Execution",
        iconName: "Skull",
        description: "If enemy is under 11% health: instantly kill; otherwise deal 80 damage.",
        cooldown: 5,
        manaCost: 42,
      },
      {
        name: "Executioner's Zeal",
        iconName: "Flame",
        description: "Passive: Each basic attack reduces Divine Execution’s cooldown by 1.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Oath of Finality",
        iconName: "Heart",
        description: "Passive: When you drop below 100% HP,spell damage is increased by 30%.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Relentless Verdict",
        iconName: "Sword",
        description: "Passive: If Divine Execution fails to kill, your next attack deals 55% damage.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Godbreaker’s Might",
        iconName: "Star",
        description: "Passive: Each enemy ability used against you increases Divine Execution’s damage by 12 (stacks).",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Gods's Wrath",
        iconName: "Flame",
        description: "Passive: When losing health, increase attack by 10% (stacks)",
        cooldown: 0,
        manaCost: 0,
      },
    ],
  },

  Archon: {
    health: 1880,
    attackMin: 34,
    attackMax: 40,
    mana: 132,
    maxMana: 132,
    description: "Radiant arbiter — order and judgment.",
    abilities: [
    {
      name: "Apotheosis",
      iconName: "Crown",
      description:
        "Ultimate: Deal 88–108 radiant damage, dispel 1 positive effect, and gain +18% damage & +18% damage reduction for 2 turns.",
      cooldown: 9,
      manaCost: 58,
    },

    // === 5 PASSIVES ===
    { 
      name: "Perfect Form", 
      iconName: "Shield", 
      description: "Passive: The first harmful effect on you each turn has its duration reduced by 1.", 
      cooldown: 0, manaCost: 0 
    },
    { 
      name: "Decree", 
      iconName: "ScrollText", 
      description: "Passive: Your dispels remove 1 additional positive effect.", 
      cooldown: 0, manaCost: 0 
    },
    { 
      name: "Seraphic Flow", 
      iconName: "Wand2", 
      description: "Passive: While above 60% mana, your spell damage is increased by 10%.", 
      cooldown: 0, manaCost: 0 
    },
    { 
      name: "Aegis of Order", 
      iconName: "ShieldCheck", 
      description: "Passive: The first hit you take each turn is reduced by 30 damage and you gain 10 mana.", 
      cooldown: 0, manaCost: 0 
    },
    { 
      name: "Judicial Pressure", 
      iconName: "Gavel", 
      description: "Passive: Enemy abilities cost +5 mana.", 
      cooldown: 0, manaCost: 0 
    },
    ],
  },
};
