import { LucideIcon } from "lucide-react";
import * as Icons from "lucide-react";

export interface PlayerClassAbility {
  name: string;
  iconName: string;
  description: string;
  /** Cooldown in seconds (real-time in battle). */
  cooldown: number;
  manaCost: number;
}

export interface PlayerClass {
  health: number;
  attackMin: number;
  attackMax: number;
  mana: number;
  maxMana: number;
  description: string;
  abilities: PlayerClassAbility[];
}

export const getIconByName = (name: string): LucideIcon => {
  const icon = (Icons as unknown as Record<string, LucideIcon>)[name];
  return icon && typeof icon === "function" ? icon : Icons.HelpCircle;
};

export const PLAYER_CLASSES: Record<string, PlayerClass> = {
  Archer: {
    health: 1870,
    attackMin: 34,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Bow skirmisher — steady pressure",
    abilities: [
      {
        name: "Volley",
        iconName: "Target",
        description: "deal 24-38 damage",
        cooldown: 4,
        manaCost: 35,
      },
      {
        name: "Berserker Shot",
        iconName: "Eye",
        description: "Deal 30 damage and increase attack by 45%",
        cooldown: 6,
        manaCost: 32,
      },
      {
        name: "Power Shot",
        iconName: "Target",
        description: "Deal 28 damage and increase attack by 40%",
        cooldown: 5,
        manaCost: 32,
      },
      {
        name: "Arcane Quiver",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 11% while above 58% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Returning Haft",
        iconName: "Zap",
        description: "Passive: Reflect 11% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Windwall Memory",
        iconName: "Shield",
        description: "Passive: Gain a shield that blocks 12 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Archmage: {
    health: 1850,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Supreme arcanist — meteors and control.",
    abilities: [
      {
        name: "Worldbreaker",
        iconName: "Skull",
        description: "Deal 72–92 arcane damage.",
        cooldown: 4,
        manaCost: 50,
      },
      {
        name: "Meteor",
        iconName: "Flame",
        description: "Deal 58–78 fire damage",
        cooldown: 3,
        manaCost: 45,
      },
      {
        name: "Blizzard",
        iconName: "Snowflake",
        description: "Deal 52–68 frost damage and slow (−18% attack) for 2 turns.",
        cooldown: 3,
        manaCost: 45,
      },
      {
        name: "Omen Surge",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 15% while under 40% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Leyline Reservoir",
        iconName: "BatteryCharging",
        description: "Passive: Increase spell damage by 13% while above 52% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Starblink Step",
        iconName: "Zap",
        description: "Passive: Gain 9% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Archon: {
    health: 1880,
    attackMin: 34,
    attackMax: 40,
    mana: 132,
    maxMana: 132,
    description: "Radiant arbiter — order and judgment.",
    abilities: [
      {
        name: "Apotheosis",
        iconName: "Crown",
        description: "Ultimate: Deal 88–108 radiant damage, dispel 1 positive effect, and gain +18% damage & +18% damage reduction for 2 turns.",
        cooldown: 9,
        manaCost: 58,
      },
      {
        name: "Perfect Form",
        iconName: "Shield",
        description: "Passive: The first harmful effect on you each turn has its duration reduced by 1.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Decree",
        iconName: "ScrollText",
        description: "Passive: Your dispels remove 1 additional positive effect.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Seraphic Flow",
        iconName: "Wand2",
        description: "Passive: While above 60% mana, your spell damage is increased by 10%.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Aegis of Order",
        iconName: "ShieldCheck",
        description: "Passive: The first hit you take each turn is reduced by 30 damage and you gain 10 mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Judicial Pressure",
        iconName: "Gavel",
        description: "Passive: Enemy abilities cost +5 mana.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Battlemage: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Spellblade hybrid",
    abilities: [
      {
        name: "Fireball",
        iconName: "Flame",
        description: "Deal 20-30 fire damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Arcane Bolt",
        iconName: "Bolt",
        description: "Deal 30 damage",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Poison",
        iconName: "Zap",
        description: "Inflict 20 poison damage",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Spellsteel Desperation",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 12% while under 46% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Bloodrun Edge",
        iconName: "Flame",
        description: "Passive: Increase attack by 12% while under 42% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Edge Aegis",
        iconName: "Shield",
        description: "Passive: Gain a shield that blocks 14 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Beastguard: {
    health: 1890,
    attackMin: 35,
    attackMax: 41,
    mana: 120,
    maxMana: 120,
    description: "Skirmisher and pet pressure",
    abilities: [
      {
        name: "Savage Maul",
        iconName: "Sword",
        description: "deal 34-50 damage",
        cooldown: 5,
        manaCost: 26,
      },
      {
        name: "Summon Wolf",
        iconName: "Dog",
        description: "Summon a wolf that deals 12 damage per turn permanently",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "Deal 12-18 damage",
        cooldown: 4,
        manaCost: 20,
      },
      {
        name: "Pack Maul",
        iconName: "Heart",
        description: "Passive: Heal for 12% of damage dealt with basic attacks.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Wind in the Reeds",
        iconName: "Zap",
        description: "Passive: Gain 8% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Alpha's Reach",
        iconName: "Target",
        description: "Passive: Increase attack by 10% while above 50% health.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Berserker: {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Execute",
        iconName: "Sword",
        description: "If enemy is under 12% health: instantly kill; otherwise deal 52 damage",
        cooldown: 9,
        manaCost: 45,
      },
      {
        name: "Blood Frenzy",
        iconName: "Flame",
        description: "Attack twice for 30-40 damage each, but take 15 self-damage",
        cooldown: 7,
        manaCost: 50,
      },
      {
        name: "Crushing Blow",
        iconName: "Sword",
        description: "deal 42-58 damage",
        cooldown: 5,
        manaCost: 32,
      },
      {
        name: "Bloodscore",
        iconName: "Flame",
        description: "Passive: Increase attack by 14% while under 38% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Rage Surge",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 11% while under 44% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Unbroken Tempo",
        iconName: "Clock",
        description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Crossbowman: {
    health: 1890,
    attackMin: 35,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Heavy crossbow — executes and volleys",
    abilities: [
      {
        name: "Aimed Shot",
        iconName: "Target",
        description: "Deal 48-68 damage",
        cooldown: 5,
        manaCost: 35,
      },
      {
        name: "Armor Piercer",
        iconName: "Crosshair",
        description: "deal 44-62 damage",
        cooldown: 5,
        manaCost: 32,
      },
      {
        name: "Power Shot",
        iconName: "Target",
        description: "Deal 58 damage and increase attack by 50%",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Sniper's Patience",
        iconName: "Crosshair",
        description: "Passive: Increase attack by 11% while above 56% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Windlass Focus",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 10% while above 54% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Spiked Carapace",
        iconName: "Zap",
        description: "Passive: Reflect 9% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  "Death Knight": {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Vampiric Strike",
        iconName: "Droplets",
        description: "Vampiric strike deal 40-80 damage with 100% healing",
        cooldown: 6,
        manaCost: 28,
      },
      {
        name: "Frost Strike",
        iconName: "Snowflake",
        description: "deal 38-54 damage",
        cooldown: 4,
        manaCost: 28,
      },
      {
        name: "Whirlwind",
        iconName: "Wind",
        description: "Whirlwind 25 damage to enemy, 8 self damage",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Rimeplate",
        iconName: "Shield",
        description: "Passive: Reduce damage taken by 11% while above 48% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Soul Harvest",
        iconName: "Skull",
        description: "Passive: Increase spell damage by 13% while under 44% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Frostmirror",
        iconName: "Zap",
        description: "Passive: Reflect 10% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  "Dragon Slayer": {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Judgment of Fate",
        iconName: "Sword",
        description: "Deal 44-62 damage. If enemy is below 35% health, deal double damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Drakefang Cleave",
        iconName: "Flame",
        description: "deal 40-56 damage",
        cooldown: 5,
        manaCost: 50,
      },
      {
        name: "Prophetic Mark",
        iconName: "Crosshair",
        description: "permanently counterattack 22% of damage taken",
        cooldown: 4,
        manaCost: 25,
      },
      {
        name: "Sigil Scales",
        iconName: "Shield",
        description: "Passive: Gain a shield that blocks 17 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Wyrmheart Stance",
        iconName: "Target",
        description: "Passive: Increase attack by 10% while above 55% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Apex Spark",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 10% while above 60% health.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Druid: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Shapeshifter and beasts",
    abilities: [
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 100 damage everyturn",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Summon Wolf",
        iconName: "Dog",
        description: "Summon a wolf that deals 12 damage per turn permanently",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Fear Howl",
        iconName: "Skull",
        description: "Become untargetable for 3 turns (stealth mode)",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Wildshape Omen",
        iconName: "Moon",
        description: "Passive: Increase spell damage by 11% while under 46% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Mistwolf Step",
        iconName: "Zap",
        description: "Passive: Gain 7% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Thorn Laceration",
        iconName: "Heart",
        description: "Passive: Heal for 9% of damage dealt with basic attacks.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  "Elemental Warden": {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Four elements",
    abilities: [
      {
        name: "Water Spout",
        iconName: "Droplets",
        description: "Deal 50 water damage , heal 30 health",
        cooldown: 4,
        manaCost: 40,
      },
      {
        name: "Spirit Bolt",
        iconName: "Sparkles",
        description: "Deal 35-45 spirit damage and restore 15 mana",
        cooldown: 4,
        manaCost: 38,
      },
      {
        name: "Fire Blast",
        iconName: "Flame",
        description: "Deal 25-35 fire damage and inflict 5 damage everyturn",
        cooldown: 3,
        manaCost: 35,
      },
      {
        name: "Conduit Mind",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 12% while above 53% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Cyclone Footing",
        iconName: "Zap",
        description: "Passive: Gain 8% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Cyclone Tempo",
        iconName: "Clock",
        description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Enchanter: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Crowd control and hexes",
    abilities: [
      {
        name: "Hex Bolt",
        iconName: "Bolt",
        description: "deal 24-36 damage",
        cooldown: 3,
        manaCost: 28,
      },
      {
        name: "Fireball",
        iconName: "Flame",
        description: "Deal 20-30 fire damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Shadow Ambush",
        iconName: "Moon",
        description: "Become untargetable for 1 turn, then strike next turn for 48-62 damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Occult Desperation",
        iconName: "Skull",
        description: "Passive: Increase spell damage by 13% while under 44% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Curseweave Reservoir",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 10% while above 56% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Hexed Aegis",
        iconName: "Shield",
        description: "Passive: Reduce damage taken by 8% while above 50% health.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Godslayer: {
    health: 1920,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Relentless duelist — execution and pressure.",
    abilities: [
      {
        name: "Divine Execution",
        iconName: "Skull",
        description: "If enemy is under 11% health: instantly kill; otherwise deal 80 damage.",
        cooldown: 5,
        manaCost: 42,
      },
      {
        name: "Executioner's Zeal",
        iconName: "Flame",
        description: "Passive: Each basic attack reduces Divine Execution’s cooldown by 1.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Oath of Finality",
        iconName: "Heart",
        description: "Passive: When you drop below 100% HP,spell damage is increased by 30%.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Relentless Verdict",
        iconName: "Sword",
        description: "Passive: If Divine Execution fails to kill, your next attack deals 55% damage.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Godbreaker’s Might",
        iconName: "Star",
        description: "Passive: Each enemy ability used against you increases Divine Execution’s damage by 12 (stacks).",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Gods's Wrath",
        iconName: "Flame",
        description: "Passive: When losing health, increase attack by 10% (stacks)",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Healer: {
    health: 1850,
    attackMin: 32,
    attackMax: 37,
    mana: 132,
    maxMana: 132,
    description: "Support striker — heals and smites",
    abilities: [
      {
        name: "Holy Smite",
        iconName: "Flame",
        description: "Deal 20-40 holy damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Heal",
        iconName: "Heart",
        description: "Restore 25% health",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Holy Nova",
        iconName: "Flame",
        description: "Deal 18-28 holy damage",
        cooldown: 3,
        manaCost: 22,
      },
      {
        name: "Litany of Light",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 10% while above 62% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Triage Bulwark",
        iconName: "Shield",
        description: "Passive: Reduce damage taken by 9% while above 55% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Mercy Shell",
        iconName: "Heart",
        description: "Passive: Gain a shield that blocks 11 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Invoker: {
    health: 1870,
    attackMin: 34,
    attackMax: 39,
    mana: 132,
    maxMana: 132,
    description: "Elemental master — fire, frost, and lightning.",
    abilities: [
      {
        name: "Fireball",
        iconName: "Flame",
        description: "Deal 52–68 fire damage.",
        cooldown: 3,
        manaCost: 35,
      },
      {
        name: "Summon Infernal",
        iconName: "Skull",
        description: "Summon an Infernal that deals 22 damage per turn for 10 turns.",
        cooldown: 16,
        manaCost: 75,
      },
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 72 damage everyturn",
        cooldown: 12,
        manaCost: 55,
      },
      {
        name: "Elemental Mastery",
        iconName: "Sparkles",
        description: "Passive: Spell immunity.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Mana Overflow",
        iconName: "BatteryCharging",
        description: "Passive: Gain +12 mana each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Elemental Harmony",
        iconName: "Atom",
        description: "Passive: Each passive pulse gain 3% attack and 2% spell damage (stacks)",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Knight: {
    health: 1920,
    attackMin: 35,
    attackMax: 41,
    mana: 118,
    maxMana: 118,
    description: "Armored hybrid — bow and blade",
    abilities: [
      {
        name: "Judgment of Fate",
        iconName: "Sword",
        description: "Deal 44-68 damage. If enemy is below 18% health, deal double damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 30-50 damage",
        cooldown: 2,
        manaCost: 50,
      },
      {
        name: "Lance Throw",
        iconName: "Target",
        description: "deal 30-46 damage",
        cooldown: 4,
        manaCost: 32,
      },
      {
        name: "Rampart Memory",
        iconName: "Shield",
        description: "Passive: Gain a shield that blocks 18 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Oathplate",
        iconName: "Shield",
        description: "Passive: Reduce damage taken by 12% while above 50% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Lance Thornfield",
        iconName: "Zap",
        description: "Passive: Reflect 8% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Lich: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Undying sorcerer",
    abilities: [
      {
        name: "Soul Harvest",
        iconName: "Moon",
        description: "deal 36-52 damage",
        cooldown: 5,
        manaCost: 32,
      },
      {
        name: "Shadow Bolt",
        iconName: "Bolt",
        description: "Deal 18-24 shadow damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Shadow Ambush",
        iconName: "Moon",
        description: "Become untargetable for 1 turn, then strike next turn for 48-64 damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Dread Insight",
        iconName: "Skull",
        description: "Passive: Increase spell damage by 15% while under 42% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Bone Spikes",
        iconName: "Zap",
        description: "Passive: Reflect 11% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Crypt Tempo",
        iconName: "Clock",
        description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Mage: {
    health: 1840,
    attackMin: 32,
    attackMax: 38,
    mana: 132,
    maxMana: 132,
    description: "Arcane duelist — fire and frost",
    abilities: [
      {
        name: "Arcane Barrage",
        iconName: "Sparkles",
        description: "deal 26-38 damage",
        cooldown: 4,
        manaCost: 28,
      },
      {
        name: "Fireball",
        iconName: "Flame",
        description: "Deal 20-30 fire damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Arcane Bolt",
        iconName: "Bolt",
        description: "Deal 30 damage",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Sapphire Reservoir",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 12% while above 55% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Codex Desperation",
        iconName: "BookOpen",
        description: "Passive: Increase spell damage by 12% while under 46% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Blinkweave",
        iconName: "Zap",
        description: "Passive: Gain 8% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Necromancer: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Minion master",
    abilities: [
      {
        name: "Summon Wraith",
        iconName: "Moon",
        description: "Summon a wraith that deals 30 damage per turn for 5 turns (stacks)",
        cooldown: 3,
        manaCost: 30,
      },
      {
        name: "Summon Zombie",
        iconName: "Zap",
        description: "Summon a zombie that deals 28 damage per turn for 5 turns (stacks)",
        cooldown: 3,
        manaCost: 30,
      },
      {
        name: "Bone Spear",
        iconName: "Skull",
        description: "deal 34-50 damage",
        cooldown: 4,
        manaCost: 28,
      },
      {
        name: "Necromancy Mastery",
        iconName: "Sparkles",
        description: "Passive: All summoned creatures deal 35% more damage always.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Withering Insight",
        iconName: "Skull",
        description: "Passive: Increase spell damage by 12% while under 43% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Grave Tempo",
        iconName: "Clock",
        description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Oracle: {
    health: 1830,
    attackMin: 32,
    attackMax: 37,
    mana: 132,
    maxMana: 132,
    description: "Seer — marks and bolts",
    abilities: [
      {
        name: "Starfall",
        iconName: "Sparkles",
        description: "deal 32-48 damage",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Astral Bolt",
        iconName: "Bolt",
        description: "Deal 24-36 damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Prophetic Mark",
        iconName: "Crosshair",
        description: "permanently counterattack 22% of damage taken",
        cooldown: 4,
        manaCost: 25,
      },
      {
        name: "Foreseen Strike",
        iconName: "Eye",
        description: "Passive: Increase attack by 8% while above 54% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Prophecy Wellspring",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 11% while above 51% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Threadwalker",
        iconName: "Zap",
        description: "Passive: Gain 9% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Paladin: {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Heavy fighter",
    abilities: [
      {
        name: "Divine Smite",
        iconName: "Sparkles",
        description: "Deal 58-72 holy damage",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Lay on Hands",
        iconName: "Heart",
        description: "restore 32% health",
        cooldown: 10,
        manaCost: 40,
      },
      {
        name: "Avenger's Rebuke",
        iconName: "Flame",
        description: "Deal 24-36 holy damage",
        cooldown: 4,
        manaCost: 24,
      },
      {
        name: "Aegis Discipline",
        iconName: "Shield",
        description: "Passive: Reduce damage taken by 10% while above 52% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Sanctified Ward",
        iconName: "Shield",
        description: "Passive: Gain a shield that blocks 16 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Zeal Thorn",
        iconName: "Zap",
        description: "Passive: Reflect 9% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Priest: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Holy support",
    abilities: [
      {
        name: "Lay on Hands",
        iconName: "Heart",
        description: "restore 32% health",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Smite Evil",
        iconName: "Flame",
        description: "Deal 22-34 holy damage",
        cooldown: 3,
        manaCost: 20,
      },
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 100 damage everyturn",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Luminous Verse",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 11% while above 61% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Sacred Desperation",
        iconName: "BookOpen",
        description: "Passive: Increase spell damage by 10% while under 48% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Clergy Bulwark",
        iconName: "Shield",
        description: "Passive: Reduce damage taken by 8% while above 50% health.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Ranger: {
    health: 1860,
    attackMin: 34,
    attackMax: 39,
    mana: 120,
    maxMana: 120,
    description: "Mobile archer — burst and focus",
    abilities: [
      {
        name: "Piercing Arrow",
        iconName: "Target",
        description: "deal 32-46 damage",
        cooldown: 5,
        manaCost: 38,
      },
      {
        name: "Aimed Shot",
        iconName: "Target",
        description: "Deal 35 damage",
        cooldown: 5,
        manaCost: 35,
      },
      {
        name: "Focused Strike",
        iconName: "ArrowRight",
        description: "Deal 25 damage and increase attack by 50%",
        cooldown: 4,
        manaCost: 30,
      },
      {
        name: "Keen Scout",
        iconName: "Target",
        description: "Passive: Increase attack by 9% while above 54% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Trailblood",
        iconName: "Heart",
        description: "Passive: Heal for 10% of damage dealt with basic attacks.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Wildstep",
        iconName: "Zap",
        description: "Passive: Gain 7% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Rogue: {
    health: 1880,
    attackMin: 34,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Bleeds and steals — tempo fighter",
    abilities: [
      {
        name: "Vampiric Strike",
        iconName: "Droplets",
        description: "Vampiric strike deal 40-80 damage with 100% healing",
        cooldown: 6,
        manaCost: 36,
      },
      {
        name: "Eviscerate",
        iconName: "Sword",
        description: "deal 28-44 damage",
        cooldown: 4,
        manaCost: 31,
      },
      {
        name: "Life Steal",
        iconName: "Heart",
        description: "Deal 20 damage and steal 20 health",
        cooldown: 6,
        manaCost: 30,
      },
      {
        name: "Backstab Instinct",
        iconName: "Moon",
        description: "Passive: Increase attack by 10% while above 52% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Shadow Tempo",
        iconName: "Clock",
        description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Smoke Dance",
        iconName: "Zap",
        description: "Passive: Gain 10% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Shaman: {
    health: 1880,
    attackMin: 35,
    attackMax: 40,
    mana: 120,
    maxMana: 120,
    description: "Spirit archer",
    abilities: [
      {
        name: "Execute",
        iconName: "Sword",
        description: "If enemy is under 25% health: instantly kill; otherwise deal 100 damage",
        cooldown: 8,
        manaCost: 45,
      },
      {
        name: "Aimed Shot",
        iconName: "Target",
        description: "Deal 28-38 damage",
        cooldown: 5,
        manaCost: 35,
      },
      {
        name: "Power Shot",
        iconName: "Target",
        description: "Deal 28 damage and increase attack by 50%",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Ancestral Bulwark",
        iconName: "Shield",
        description: "Passive: Gain a shield that blocks 14 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Hexsight Omen",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 11% while under 47% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Spirit Mist",
        iconName: "Zap",
        description: "Passive: Gain 8% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Slayer: {
    health: 1900,
    attackMin: 35,
    attackMax: 41,
    mana: 118,
    maxMana: 118,
    description: "Aggressive striker — high burst windows",
    abilities: [
      {
        name: "Execute",
        iconName: "Sword",
        description: "If enemy is under 10% health: instantly kill; otherwise deal 42 damage",
        cooldown: 9,
        manaCost: 50,
      },
      {
        name: "Whirlwind",
        iconName: "Wind",
        description: "Whirlwind 52 damage to enemy, 14 self damage",
        cooldown: 5,
        manaCost: 30,
      },
      {
        name: "Ground Slam",
        iconName: "Hammer",
        description: "deal 34-48 damage",
        cooldown: 5,
        manaCost: 25,
      },
      {
        name: "Carnage Mark",
        iconName: "Flame",
        description: "Passive: Increase attack by 13% while under 41% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Bloodlet",
        iconName: "Heart",
        description: "Passive: Heal for 13% of damage dealt with basic attacks.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Killer Instinct",
        iconName: "Skull",
        description: "Passive: Increase spell damage by 10% while under 48% health.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  TaurenChieftain: {
    health: 1940,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Totemic war leader — spirits and endurance.",
    abilities: [
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 58-72 damage",
        cooldown: 5,
        manaCost: 56,
      },
      {
        name: "Rage",
        iconName: "Flame",
        description: "Increase attack by 18% deal 38 damage",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Prophetic Mark",
        iconName: "Crosshair",
        description: "permanently counterattack 22% of damage taken",
        cooldown: 14,
        manaCost: 55,
      },
      {
        name: "Totemic Strength",
        iconName: "Megaphone",
        description: "Passive: Regenerate 20 health everyturn",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Spirit Endurance",
        iconName: "Heart",
        description: "Passive: Reincarnation ",
        cooldown: 100,
        manaCost: 0,
      },
      {
        name: "Gods's Wrath",
        iconName: "Flame",
        description: "Passive: When losing health, increase attack by 1% (stacks)",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Warlock: {
    health: 1860,
    attackMin: 33,
    attackMax: 39,
    mana: 128,
    maxMana: 128,
    description: "Shadow pact — drains and imps",
    abilities: [
      {
        name: "Vampiric Strike",
        iconName: "Droplets",
        description: "Vampiric strike deal 40-80 damage with 100% healing",
        cooldown: 6,
        manaCost: 28,
      },
      {
        name: "Fel Spike",
        iconName: "Skull",
        description: "deal 32-46 shadow damage",
        cooldown: 4,
        manaCost: 26,
      },
      {
        name: "Shadow Bolt",
        iconName: "Bolt",
        description: "Deal 18-24 shadow damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Demonic Desperation",
        iconName: "Skull",
        description: "Passive: Increase spell damage by 14% while under 43% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Fel Reservoir",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 11% while above 52% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Pact Thorns",
        iconName: "Zap",
        description: "Passive: Reflect 10% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Warlord: {
    health: 1910,
    attackMin: 36,
    attackMax: 42,
    mana: 118,
    maxMana: 118,
    description: "Battlefield commander",
    abilities: [
      {
        name: "Commanding Strike",
        iconName: "Sword",
        description: "Deal 44-62 damage,Increase attack by 38%",
        cooldown: 8,
        manaCost: 50,
      },
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 30-50 damage",
        cooldown: 2,
        manaCost: 50,
      },
      {
        name: "Sundering Blow",
        iconName: "Hammer",
        description: "deal 36-50 damage",
        cooldown: 5,
        manaCost: 32,
      },
      {
        name: "Command Presence",
        iconName: "Target",
        description: "Passive: Increase attack by 9% while above 57% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Veteran's Riposte",
        iconName: "Zap",
        description: "Passive: Reflect 8% of damage taken from attacks.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "War Drums",
        iconName: "Clock",
        description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Warrior: {
    health: 1910,
    attackMin: 35,
    attackMax: 41,
    mana: 118,
    maxMana: 118,
    description: "Frontline duelist — shields and shouts",
    abilities: [
      {
        name: "Shield Bash",
        iconName: "Shield",
        description: "deal 48-62 damage",
        cooldown: 5,
        manaCost: 24,
      },
      {
        name: "Cleave",
        iconName: "Sword",
        description: "deal 38-52 damage",
        cooldown: 4,
        manaCost: 18,
      },
      {
        name: "Fortifying Cry",
        iconName: "Shield",
        description: "Gain a shield that blocks 35 damage everyturn",
        cooldown: 6,
        manaCost: 22,
      },
      {
        name: "Plate Discipline",
        iconName: "Shield",
        description: "Passive: Reduce damage taken by 9% while above 51% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Shieldwall Memory",
        iconName: "Shield",
        description: "Passive: Gain a shield that blocks 16 damage each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Veteran's Reach",
        iconName: "Target",
        description: "Passive: Increase attack by 8% while above 58% health.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Witcher: {
    health: 1910,
    attackMin: 35,
    attackMax: 41,
    mana: 125,
    maxMana: 125,
    description: "Monster-slaying swordsman — signs and alchemy.",
    abilities: [
      {
        name: "Blood Frenzy",
        iconName: "Flame",
        description: "Attack twice for 40-52 damage each, but take 15 self-damage",
        cooldown: 7,
        manaCost: 50,
      },
      {
        name: "Igni Sign",
        iconName: "Flame",
        description: "Deal 52–68 fire damage",
        cooldown: 5,
        manaCost: 45,
      },
      {
        name: "Rally",
        iconName: "Heart",
        description: "Restore 55 health points",
        cooldown: 3,
        manaCost: 5,
      },
      {
        name: "Mutagens",
        iconName: "Beaker",
        description: "Passive: Increase attack by 28% while above 50% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Monster Killer",
        iconName: "BookOpen",
        description: "Passive: Increase spell damage by 28% while under 50% health.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Alchemy Mastery",
        iconName: "FlaskRound",
        description: "Passive: All healing received is 35% stronger while under 50% health.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  },
  Wizard: {
    health: 1840,
    attackMin: 32,
    attackMax: 38,
    mana: 128,
    maxMana: 128,
    description: "Battle cleric — wards and smites",
    abilities: [
      {
        name: "Holy Smite",
        iconName: "Flame",
        description: "Deal 20-40 holy damage",
        cooldown: 3,
        manaCost: 25,
      },
      {
        name: "Searing Light",
        iconName: "Bolt",
        description: "deal 28-40 damage",
        cooldown: 3,
        manaCost: 22,
      },
      {
        name: "Sacred Ward",
        iconName: "Shield",
        description: "Gain a shield that blocks 100 damage everyturn",
        cooldown: 6,
        manaCost: 40,
      },
      {
        name: "Arcane Reservoir",
        iconName: "Sparkles",
        description: "Passive: Increase spell damage by 12% while above 54% mana.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Runic Cadence",
        iconName: "Clock",
        description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      },
      {
        name: "Phase Slip",
        iconName: "Zap",
        description: "Passive: Gain 8% evasion each passive pulse.",
        cooldown: 0,
        manaCost: 0,
      }
    ],
  }
};
