import type { PlayerClassAbility } from "../src/components/game/class-data";

/**
 * Three passives per class — each kit mixes different parsed hooks (see passive-runtime).
 * Most classes skip HP/mana pulse regen; role-based per-second regen still applies from class-categories.
 */
export const PER_CLASS_PASSIVES: Record<string, PlayerClassAbility[]> = {
  Archer: [
    {
      name: "Arcane Quiver",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 11% while above 58% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Returning Haft",
      iconName: "Zap",
      description: "Passive: Reflect 11% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Windwall Memory",
      iconName: "Shield",
      description: "Passive: Gain a shield that blocks 12 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Archmage: [
    {
      name: "Omen Surge",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 15% while under 40% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Leyline Reservoir",
      iconName: "BatteryCharging",
      description: "Passive: Increase spell damage by 13% while above 52% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Starblink Step",
      iconName: "Zap",
      description: "Passive: Gain 9% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Battlemage: [
    {
      name: "Spellsteel Desperation",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 12% while under 46% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Bloodrun Edge",
      iconName: "Flame",
      description: "Passive: Increase attack by 12% while under 42% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Edge Aegis",
      iconName: "Shield",
      description: "Passive: Gain a shield that blocks 14 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Beastguard: [
    {
      name: "Pack Maul",
      iconName: "Heart",
      description: "Passive: Heal for 12% of damage dealt with basic attacks.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Wind in the Reeds",
      iconName: "Zap",
      description: "Passive: Gain 8% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Alpha's Reach",
      iconName: "Target",
      description: "Passive: Increase attack by 10% while above 50% health.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Berserker: [
    {
      name: "Bloodscore",
      iconName: "Flame",
      description: "Passive: Increase attack by 14% while under 38% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Rage Surge",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 11% while under 44% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Unbroken Tempo",
      iconName: "Clock",
      description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Crossbowman: [
    {
      name: "Sniper's Patience",
      iconName: "Crosshair",
      description: "Passive: Increase attack by 11% while above 56% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Windlass Focus",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 10% while above 54% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Spiked Carapace",
      iconName: "Zap",
      description: "Passive: Reflect 9% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  "Death Knight": [
    {
      name: "Rimeplate",
      iconName: "Shield",
      description: "Passive: Reduce damage taken by 11% while above 48% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Soul Harvest",
      iconName: "Skull",
      description: "Passive: Increase spell damage by 13% while under 44% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Frostmirror",
      iconName: "Zap",
      description: "Passive: Reflect 10% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  "Dragon Slayer": [
    {
      name: "Sigil Scales",
      iconName: "Shield",
      description: "Passive: Gain a shield that blocks 17 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Wyrmheart Stance",
      iconName: "Target",
      description: "Passive: Increase attack by 10% while above 55% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Apex Spark",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 10% while above 60% health.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Druid: [
    {
      name: "Wildshape Omen",
      iconName: "Moon",
      description: "Passive: Increase spell damage by 11% while under 46% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Mistwolf Step",
      iconName: "Zap",
      description: "Passive: Gain 7% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Thorn Laceration",
      iconName: "Heart",
      description: "Passive: Heal for 9% of damage dealt with basic attacks.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  "Elemental Warden": [
    {
      name: "Conduit Mind",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 12% while above 53% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Cyclone Footing",
      iconName: "Zap",
      description: "Passive: Gain 8% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Cyclone Tempo",
      iconName: "Clock",
      description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Enchanter: [
    {
      name: "Occult Desperation",
      iconName: "Skull",
      description: "Passive: Increase spell damage by 13% while under 44% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Curseweave Reservoir",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 10% while above 56% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Hexed Aegis",
      iconName: "Shield",
      description: "Passive: Reduce damage taken by 8% while above 50% health.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Healer: [
    {
      name: "Litany of Light",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 10% while above 62% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Triage Bulwark",
      iconName: "Shield",
      description: "Passive: Reduce damage taken by 9% while above 55% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Mercy Shell",
      iconName: "Heart",
      description: "Passive: Gain a shield that blocks 11 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Invoker: [
    {
      name: "Elemental Mastery",
      iconName: "Sparkles",
      description: "Passive: Spell immunity.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Mana Overflow",
      iconName: "BatteryCharging",
      description: "Passive: Gain +12 mana each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Elemental Harmony",
      iconName: "Atom",
      description: "Passive: Each passive pulse gain 3% attack and 2% spell damage (stacks)",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Knight: [
    {
      name: "Rampart Memory",
      iconName: "Shield",
      description: "Passive: Gain a shield that blocks 18 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Oathplate",
      iconName: "Shield",
      description: "Passive: Reduce damage taken by 12% while above 50% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Lance Thornfield",
      iconName: "Zap",
      description: "Passive: Reflect 8% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Lich: [
    {
      name: "Dread Insight",
      iconName: "Skull",
      description: "Passive: Increase spell damage by 15% while under 42% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Bone Spikes",
      iconName: "Zap",
      description: "Passive: Reflect 11% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Crypt Tempo",
      iconName: "Clock",
      description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Mage: [
    {
      name: "Sapphire Reservoir",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 12% while above 55% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Codex Desperation",
      iconName: "BookOpen",
      description: "Passive: Increase spell damage by 12% while under 46% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Blinkweave",
      iconName: "Zap",
      description: "Passive: Gain 8% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Necromancer: [
    {
      name: "Necromancy Mastery",
      iconName: "Sparkles",
      description: "Passive: All summoned creatures deal 35% more damage always.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Withering Insight",
      iconName: "Skull",
      description: "Passive: Increase spell damage by 12% while under 43% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Grave Tempo",
      iconName: "Clock",
      description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Oracle: [
    {
      name: "Foreseen Strike",
      iconName: "Eye",
      description: "Passive: Increase attack by 8% while above 54% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Prophecy Wellspring",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 11% while above 51% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Threadwalker",
      iconName: "Zap",
      description: "Passive: Gain 9% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Paladin: [
    {
      name: "Aegis Discipline",
      iconName: "Shield",
      description: "Passive: Reduce damage taken by 10% while above 52% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Sanctified Ward",
      iconName: "Shield",
      description: "Passive: Gain a shield that blocks 16 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Zeal Thorn",
      iconName: "Zap",
      description: "Passive: Reflect 9% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Priest: [
    {
      name: "Luminous Verse",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 11% while above 61% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Sacred Desperation",
      iconName: "BookOpen",
      description: "Passive: Increase spell damage by 10% while under 48% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Clergy Bulwark",
      iconName: "Shield",
      description: "Passive: Reduce damage taken by 8% while above 50% health.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Ranger: [
    {
      name: "Keen Scout",
      iconName: "Target",
      description: "Passive: Increase attack by 9% while above 54% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Trailblood",
      iconName: "Heart",
      description: "Passive: Heal for 10% of damage dealt with basic attacks.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Wildstep",
      iconName: "Zap",
      description: "Passive: Gain 7% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Rogue: [
    {
      name: "Backstab Instinct",
      iconName: "Moon",
      description: "Passive: Increase attack by 10% while above 52% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Shadow Tempo",
      iconName: "Clock",
      description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Smoke Dance",
      iconName: "Zap",
      description: "Passive: Gain 10% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Shaman: [
    {
      name: "Ancestral Bulwark",
      iconName: "Shield",
      description: "Passive: Gain a shield that blocks 14 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Hexsight Omen",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 11% while under 47% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Spirit Mist",
      iconName: "Zap",
      description: "Passive: Gain 8% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Slayer: [
    {
      name: "Carnage Mark",
      iconName: "Flame",
      description: "Passive: Increase attack by 13% while under 41% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Bloodlet",
      iconName: "Heart",
      description: "Passive: Heal for 13% of damage dealt with basic attacks.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Killer Instinct",
      iconName: "Skull",
      description: "Passive: Increase spell damage by 10% while under 48% health.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Warlock: [
    {
      name: "Demonic Desperation",
      iconName: "Skull",
      description: "Passive: Increase spell damage by 14% while under 43% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Fel Reservoir",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 11% while above 52% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Pact Thorns",
      iconName: "Zap",
      description: "Passive: Reflect 10% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Warlord: [
    {
      name: "Command Presence",
      iconName: "Target",
      description: "Passive: Increase attack by 9% while above 57% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Veteran's Riposte",
      iconName: "Zap",
      description: "Passive: Reflect 8% of damage taken from attacks.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "War Drums",
      iconName: "Clock",
      description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Warrior: [
    {
      name: "Plate Discipline",
      iconName: "Shield",
      description: "Passive: Reduce damage taken by 9% while above 51% health.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Shieldwall Memory",
      iconName: "Shield",
      description: "Passive: Gain a shield that blocks 16 damage each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Veteran's Reach",
      iconName: "Target",
      description: "Passive: Increase attack by 8% while above 58% health.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
  Wizard: [
    {
      name: "Arcane Reservoir",
      iconName: "Sparkles",
      description: "Passive: Increase spell damage by 12% while above 54% mana.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Runic Cadence",
      iconName: "Clock",
      description: "Passive: Reduce all ability cooldowns by 1 second each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
    {
      name: "Phase Slip",
      iconName: "Zap",
      description: "Passive: Gain 8% evasion each passive pulse.",
      cooldown: 0,
      manaCost: 0,
    },
  ],
};
